#############################################################################
# Copyright (c) 2026 BootCtrl
#
# SPDX-License-Identifier: EPL-2.0
#############################################################################

add_subdirectory(core)
add_subdirectory(backend)
add_subdirectory(preprocessing)
add_subdirectory(inference)
add_subdirectory(postprocessing)
add_subdirectory(management)
